

  "version": "0.2",
  "phases": {
    "pre_build": {
      "commands": [
        "echo Logging in to Amazon ECR...",
        "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY",
        "echo Installing dependencies...",
        "npm ci",
        "echo Building TypeScript...",
        "npm run build"
      ]
    },
    "build": {
      "commands": [
        "echo Building Docker image...",
        "docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .",
        "echo Tagging image...",
        "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPOSITORY:$IMAGE_TAG",
        "docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPOSITORY:latest",
        "echo Pushing image to ECR...",
        "docker push $ECR_REPOSITORY:$IMAGE_TAG",
        "docker push $ECR_REPOSITORY:latest"
      ]
    },
    "post_build": {
      "commands": [
        "echo Build completed successfully"
      ]
    }
  }
}




