package cl.gob.sna.gtime.vo;

public enum TipoValidacion {
	GTIME_TIPO("E: Mensaje no corresponde a INGRESO de GTIME"),
	USUARIO_NO_EXISTE("E:Usuario no Existe "),
	LOGIN_DIGITADOR_NULL("E:Debe indicar el atributo [login] "),
	LOGIN_DIGITADOR("E:El atributo [login] debe ser <=50 caracteres"),
	NUMERO_REFERENCIA("E:El atributo [numero-referencia] debe ser <=200 caracteres"),
	NUMERO_REFERENCIA_NULL("E:Debe indicar el atributo [numero-referencia]"),
	TOTAL_BULTOS("E:Se debe indicar el Total de Bultos en la Guía TIME"),
	TOTAL_BULTOS_NULL("E:Debe indicar el atributo [total-bultos]"),
	TOTAL_PESO("E:Debe indicar el Total Peso en la Guia TIME "),
	TOTAL_PESO_NULL("E:Debe indicar el atributo [total-peso]"),
	UNIDAD_PESO_NULL("E:Debe indicar el atributo [unidad-peso] para el Total de Peso"),
	UNIDAD_PESO_UNEXIST("E:La unidad de peso [[1?]] no existe en los registros del Sistema"),
	TOTAL_VOLUMEN("E:El atributo [total-volumen] debe ser mayor que cero"),
	UNIDAD_VOLUMEN_UNEXIST("E:La unidad de volumen [[1?]] no existe en los registros del Sistema"),
	UNIDAD_VOLUMEN_NULL("E:Se debe indicar un valor para la Unidad de Volumen en la Guía TIME"),
	TOTAL_ITEM("E:Se debe indicar un valor para el Total de Items en la Guía TIME"),
	TOTAL_ITEM_NULL("E:Debe indicar el atributo [total-item]"),
	VALOR_DECLARADO("E:Se debe indicar un valor para Valor Declarado en la Guía TIME"),
	VALOR_DECLARADO_NULL("E:El atributo [valor-declarado] debe ser un valor mayor a cero"),
	MONEDA_VALOR_UNEXIST("E:La moneda [[1?]] del Valor Declarado no existe en los registros del Sistema"),
	MONEDA_VALOR_NULL("E:Debe indicar el atributo [moneda-valor] para el Valor Declarado de las mercancías"),
	PARCIAL_NULL("E:Debe ingresar el atributo [parcial]"),
	PARCIAL("E:El valor del atributo [parcial], debe ser S o N"),
	TIPO_OPERACION_NULL("E:Debe indicar el atributo [tipo-operacion]"),
	TIPO_OPERACION("E:El Tipo Operación debe ser ''I''(Ingreso) o ''S''(Salida) o ''TR''(Tránsito) o ''TRB''(Transbordo)"),
	FECHAS_REPETIDAS("E:La Fecha [[1?]] se repite [2?] veces"),
	FECHAS_SIN_NOMBRE("E:En Fechas[[1?]] debe indicar el atributo [nombre]"),
	FECHAS_LARGO_NOMBRE("E:En Fechas[[1?]] el largo del atributo [nombre] debe ser <= 10 caracteres"),	
	FECHAS_TIPO_FECHA_NO_DEFINIDO("E:En Fechas[[1?]] el tipo fecha [[2?]] no se encuentra definido en este Tipo de Documento"),
	FECHAS_FECHA_CREACION_NO_PERMITIDA("E:En Fechas[[1?]] no debe registrarse la Fecha de Creación"),
	FECHAS_ERROR_PROCESAR_NOMBRE("E:En Fechas[[1?]] error al procesar atributo [nombre]"),
	FECHAS_SIN_VALOR("E:En Fechas[[1?]] debe indicar el atributo [valor]"),
	FECHAS_ERROR_PROCESAR_VALOR("E:En Fechas[[1?]] error al procesar atributo [valor]"),
	FECHAS_EMISION_NO_VALIDA("E:La Fecha de Emisión debe ser menor a la Fecha de Envío del Mensaje"),
	FECHAS_FEM_NO_VALIDA("E:La Fecha de Emisión debe ser menor a la Fecha de Envío del Mensaje"),
	PARTICIPACIONES_SIN_NOMBRE("E:En Participacion[[1?]] debe indicar el atributo [nombre]"),
	PARTICIPACIONES_LARGO_NOMBRE("E:En Participacion[[1?]] el largo del atributo [nombre] debe ser <= 5 caracteres"),
	PARTICIPACIONES_TIPO_ID("E:En Participacion[[1?]] el largo máximo de [tipo-id] es 30"),
	PARTICIPACIONES_NACION_ID("E:En Participacion[[1?]]  el largo del atributo [nacion-id] debe ser <= 5 caracteres"),
	PARTICIPACIONES_VALOR_ID("E:En Participacion[[1?]] el largo del atributo [valor-id] debe ser <= 255 caracteres"),
	PARTICIPACIONES_SIN_NOMBRES("E:En Participacion[[1?]] debe indicar el atributo [nombres]"),
	PARTICIPACIONES_LARGO_NOMBRES("E:En Participacion[[1?]] el largo del atributo [nombres] debe ser <= 255 caracteres"),
	PARTICIPACIONES_DIRECCION("E:En Participacion[[1?]] el largo del atributo [direccion] debe ser <= 255 caracteres"),
	PARTICIPACIONES_PAIS_NO_EXISTE("E:En Participacion[[1?]] el País indicado en la dirección, no se encuentra en los registros del Sistema"),
	PARTICIPACIONES_DOCROLTIPODOC_NO_EXISTE("E:En Participacion[[1?]] el Rol [[2?]] no se encuentra definido en este Tipo de Documento"),
	PARTICIPACIONES_TIPO_ALMACENISTA_TIPO_ID("E:El Almacenista debe tener Tipo de Identificador"),
	PARTICIPACIONES_TIPO_ALMACENISTA_TIPO_ID_ADU("E:El Almacenista no debe tener como Tipo de Identificador ADU."),
	PARTICIPACIONES_TIPO_ALMACENISTA_NACION_ID("E:El Almacenista debe tener Nacionalidad"),
	PARTICIPACIONES_TIPO_ALMACENISTA_VALOR_ID("E:El Almacenista debe tener Identificador"),
	PARTICIPACIONES_TIPO_ALMACENISTA_COD_PAIS("E:El Almacenista debe tener Código de País"),
	PARTICIPACIONES_TIPO_TRANSPORTISTA_TIPO_ID("E:El Transportista debe tener Tipo de Identificador"),
	PARTICIPACIONES_TIPO_TRANSPORTISTA_NACION_ID("E:El Transportista debe tener Nacionalidad"),
	PARTICIPACIONES_TIPO_TRANSPORTISTA_VALOR_ID("E:El Transportista debe tener Identificador"),
	PARTICIPACIONES_TIPO_TRANSPORTISTA_COD_PAIS("E:El Transportista debe tener Código de País"),
	PARTICIPACIONES_TIPO_EMISOR_TIPO_ID("E:El Emisor debe tener Tipo de Identificador"),
	PARTICIPACIONES_TIPO_EMISOR_NACION_ID("E:El Emisor debe tener Nacionalidad"),
	PARTICIPACIONES_TIPO_EMISOR_VALOR_ID("E:El Emisor debe tener Identificador"),
	PARTICIPACIONES_TIPO_EMISOR_OPERADOR_COURIER_NO_EXISTE("E:El Emisor con identificación :[1?] no está registrado como Operador 'COURIER' Vigente."),
	PARTICIPACIONES_TIPO_CONSIGNANTE_SIN_NACION("E:El Consignante debe tener Nacionalidad"),
	PARTICIPACIONES_TIPO_CONSIGNANTE_SIN_PAIS("E:El Consignante debe tener Código de País"),
	PARTICIPACIONES_TIPO_CONSIGNATARIO_TIPO_ID("E:El Consignatario debe tener Tipo de Identificador"),
	PARTICIPACIONES_TIPO_CONSIGNATARIO_SIN_NACION("E:El Consignatario debe tener Nacionalidad"),
	PARTICIPACIONES_TIPO_CONSIGNATARIO_SIN_PAIS("E:El Consignatario debe tener Código de País"),
	PARTICIPACIONES_TIPO_CONSIGNATARIO_VALOR_ID_TIPO_RUT("E:Para Consignatario, si el tipo id es RUT debe ingresar el rut en el campo Valor Id."),
	PARTICIPACIONES_TIPO_CONSIGNATARIO_VALOR_ID_TIPO_RUT_ERRONEO("E: En Participacion[[1?]] Rut Erróneo"),
	PARTICIPACIONES_SIN_TRANSPORTISTA("E:El Tipo de Documento [[1?]] debe contener al TRANSPORTISTA"),
	PARTICIPACIONES_SIN_EMISOR("E:El Tipo de Documento [[1?]] debe contener al EMISOR"),
	PARTICIPACIONES_SIN_CONSIGNANTE("E:El Tipo de Documento [[1?]] debe contener al CONSIGNANTE"),
	PARTICIPACIONES_SIN_CONSIGNATARIO("E:El Tipo de Documento [[1?]] debe contener al CONSIGNATARIO"),
	EMISOR_REFERENCIA_ASOCIADA("E:Ya se encuentra asociado el Número de Referencia al Emisor"),
	REFERENCIA_SIN_REFERENCIA("E:En Referencias, debe existir una referencia al Manifiesto Courier asociado a la Guia Courier"),
	REFERENCIA_MAXIMO_REFERENCIA("E:Se debe indicar sola una referencia del tipo REF"),
	REFERENCIA_TIPO_NULO("E:En Referencias[[1?]] debe indicar el atributo [tipo-referencia]"),
	REFERENCIA_TIPO_DOCUMENTO_NULO("E:En Referencias[[1?]] debe indicar el atributo [tipo-documento] de referencia"),
	REFERENCIA_TIPO_DOCUMENTO_NO_REGISTRADO("E:En Referencias[[1?]] el Tipo de Documento [[2?]] no se encuentra registrado en los Sistemas"),
	REFERENCIA_TIPO_DOCUMENTO_NO_RELACIONADO("E:En Referencias[[1?]] el Tipo de relación [[2?]] no está permitida entre los Tipos de Documentos [3?] y ' [4?]"),
	REFERENCIA_SIN_ATRIBUTO_NUMERO("E:En Referencias[[1?]] debe indicar el atributo [numero] con el Número del Documento de referencia"),
	REFERENCIA_SIN_FECHA("E:En Referencias[[1?]] debe indicar el atributo [fecha] con la fecha de emisión del Documento de referencia"),
	REFERENCIA_SIN_REFERENCIA_DOCUMENTAL("E:Este tipo de documento debe contener Referencias Documentales."),
	REFERENCIA_REF_EMI_FEM_NO_REGISTRADO("E:En Referencias[[1?]] El [2?] con Emisor [3?], fecha Emision [4?] y Numero Referencia [5?] no se encuentra en los registros del sistema"),
	REFERENCIA_MANIFIESTO_ANULADO("E:El Manifiesto Courier Nº [1?] con Fecha Emisión [[2?]] y Emisor [[3?]] se encuentra ANULADO"),
	REFERENCIA_EMISOR_TIPO_NO_CORRESPONDE("E:El Tipo de Id del Emisor de la Guía Time no corresponde al declarado en el Manifiesto Referenciado"),
	REFERENCIA_EMISOR_VALOR_NO_CORRESPONDE("E:El Valor Id del Emisor de la Guía Time no corresponde al declarado en el Manifiesto Referenciado"),
	REFERENCIA_MANIFIESTO_REFERENCIADO_INGRESO("E:El Tipo de Manifiesto referenciado es de Ingreso"),
	REFERENCIA_MANIFIESTO_REFERENCIADO_SALIDA("E:El Tipo de Manifiesto referenciado es de Salida"),
	REFERENCIA_EMISOR_NO_REGISTRADO("E:En Referencias[[1?]] el emisor no se encuentra registrado en los Sistemas"),
	REFERENCIA_EMISOR_INCOMPLETO("E:En Referencias[[1?]] debe indicar [tipo-id-emisor], [nac-id-emisor] y [valor-id-emisor]"),
	REFERENCIA_EMISOR_SIN_NOMBRE("E:En Referencias[[1?]] debe indicar el atributo [emisor] con el nombre del Emisor del Documento referenciado"),
	LOCACION_NOMBRE_NULL("E:Locacion[[1?]] Debe indicar el atributo [nombre]"),
	LOCACION_NOMBRE_LARGO("E:Locacion[[1?]] el largo del atributo [nombre] debe ser <= 30 caracteres"),
	LOCACION_NOMBRE_INVALIDO_TIPO_DOC("E:Locacion[[1?]] el Tipo de Locacion [[2?]] no esta definido para este Tipo de Documento"),
	LOCACION_COD_NULL("E:Locacion[[1?]] Debe indicar el atributo [codigo]"),
	LOCACION_COD_LARGO("E:Locacion[[1?]] el largo del atributo [codigo] debe ser <= 5 caracteres"),
	LOCACION_DESCRIPCION_NULL("E:Locacion[[1?]] Debe indicar el atributo [descripcion]"),
	LOCACION_DESCRIPCION_LARGO("E:Locacion[[1?]] el largo del atributo [descripcion] debe ser <= 255 caracteres"),
	LOCACION_COD_NO_ENCONTRADO("E:En Locaciones[[1?]], para [[2?]]: El código de locación:[[3?]] no se encuentra registrado en los Sistemas."),
	LOCACION_DESCRIPCION_NO_COINCIDE("W:El Código de la Locación [[1?]] no coincide con la descripción en los sistemas"),
	LOCACION_SIN_PAIS("E:La Locación debe tener asociado un País"),
	LOCACION_PUERTO_EMBARQUE_ES_CL("E:La Locación [[1?]] del Puerto de Embarque debe ser distinta a una Locación Chilena"),
	LOCACION_LUGAR_RECEPCION_NO_CL("E:La Locación [[1?]] del Lugar de Recepción de la Mcía. debe ser distinta a una Locación Chilena"),
	LOCACION_PUERTO_DESEMBARQUE_NO_CL("E:La Locación [[1?]] del Puerto de Desembarque no corresponde a una Locación Chilena"),
	LOCACION_LUGAR_DESTINO_NO_CL("E:La Locación [[1?]] del Lugar de Destino no corresponde a una Locación Chilena"),
	LOCACION_LUGAR_ENTREGA_NO_CL("E:La Locación [[1?]] del Lugar de Entrega de la Mcía. no corresponde a una Locación Chilena"),
	LOCACION_DESTINO_NO_CL("E:La Locación [[1?]] del Lugar de Destino Final debe ser distinta a una Locación Chilena"),
	LOCACION_PUERTO_EMBARQUE_NO_CL("E:La Locación [[1?]] del Puerto de Embarque no corresponde a un Puerto Chileno"),
	LOCACION_RECEPCION_NO_CL("E:La Locación [[1?]] del Lugar de Recepción de la Mcía. no corresponde a un Puerto Chileno"),
	LOCACION_PUERTO_DESEMBARQUE_NO_CL_2("E:La Locación [[1?]] del Puerto de Desembarque debe ser distinta a un Puerto Chileno"),
	LOCACION_LUGAR_DESTINO_NO_CL_2("E:La Locación [[1?]] del Lugar de Destino debe ser distinta a un Puerto Chileno"),
	LOCACION_LUGAR_ENTREGA_NO_CL_2("E:La Locación [[1?]] del Lugar de Entrega de la Mcía. debe ser distinta a un Puerto Chileno"),
	LOCACION_PUERTO_EMBARQUE_NO_CL_2("E:La Locación [[1?]] del Puerto de Embarque no corresponde a una Locación Chilena"),
	LOCACION_PUERTO_DESEMBARQUE_ES_CL("E:La Locación [[1?]] del Puerto de Desembarque debe ser distinta a una Locación Chilena"),
	LOCACION_LUGAR_DESTINO_ES_CL("E:La Locación [[1?]] del Lugar de Destino debe ser distinta a una Locación Chilena"),
	LOCACION_MINIMO_REGISTRO("E:Debe ingresar las Locaciones para el Tipo de Documento[[1?]]"),
	LOCACION_PUERTO_EMBARQUE_OBLIGATORIO("E:El Tipo de Documento [[1?]] debe contener el Puerto de Embarque"),
	LOCACION_PUERTO_DESEMBARQUE_OBLIGATORIO("E:El Tipo de Documento [[1?]] debe contener el Puerto de Desembarque"),
	OBSERVACION_CONTENIDO_NULL("E:En Observaciones[[1?]] se debe indicar el atributo [contenido]"),
	OBSERVACION_TIPO_DOC_NO_EXISTE("E:En Observaciones[[1?]] el tipo [[2?]] no se encuentra definido para el Tipo de Documento [[3?]]"),
	OBSERVACION_NOMBRE_NO_GRAL("E:En Observaciones[[1?]] cuando es una guia de Ingreso, el atributo [nombre] debe ser 'GRAL'"),
	ITEMS_SIN_NRO_ITEM("E:Se debe indicar el Número del Item"),
	ITEMS_NRO_ITEM_NO_CORRESPONDE ("E:El valor del Número de Items no corresponde"),
	ITEMS_NRO_ITEM_CON_SECUENCIA_NO_CORRESPONDE("E:La secuencia en los Items no corresponde"),
	ITEMS_SIN_MARCAS("E:Se debe indicar atributo [marcas] en el Item[[1?]]"),
	ITEMS_SIN_TIPO_BULTO("E:Se debe indicar el Tipo de Bulto en el Item[[1?]]"),
	ITEMS_TIPO_BULTO_NO_EXISTE("E:Item[[1?]] El Tipo de Bulto [[2?]] no existe en los registros del Sistema"),
 	ITEMS_SIN_UNIDAD_PESO("E:Item[[1?]] Debe indicar el atributo [unidad-peso]"),
	ITEM_UNIDAD_PESO_NO_EXISTE("E:Item[[1?]] La Unidad de Peso [[2?]] no existe en los registros del Sistema"),
	ITEM_UNIDAD_PESO_DISTINTA_ENCABEZADO("E:la Unidad de Peso declarada del Encabezado no corresponde a la del item[[1?]]"),
	PRODUCTO_SIN_DESCRIPCION("E:En Productos[[1?]], se debe indicar la Descripción del Producto en el item[[2?]]"),
	PRODUCTO_SIN_UNIDAD_MEDIDA("E:En Productos[[1?]], se debe indicar la Unidad de Medida del Producto en el item[[2?]]"),
	PRODUCTO_UNIDAD_MEDIDA_NO_EXISTE("E:En Productos[[1?]] en el item[[2?]] la Unidad de Medida [[3?]] no existe en los registros del Sistema"),
	PRODUCTO_SIN_CANTIDAD("E:En Productos[[1?]], se debe indicar la Cantidad del Producto en el item[[2?]]"),
	PRODUCTO_NO_CANTIDAD_MAYOR_CERO("E:En Productos[[1?]] en el item[[2?]] en el atributo [cantidad] debe indicar un valor mayor que cero"),
	PRODUCTO_SIN_VALOR_DECLARADO("E:En Productos[[1?]], se debe indicar el Valor Declarado en el item[[2?]]"),
	PRODUCTO_SIN_MONEDA("E:En Productos[[1?]], se debe indicar la Moneda del Producto en el item[[2?]]"),
	ITEMS_SIN_ITEMS("E:Se debe indicar al menos un ITEM en el documento"),
	ITEMS_SIN_PRODUCTOS("E:En Productos, se debe indicar el Producto en el item[[1?]]"),
	ITEMS_TIPO_BULTO_REPETIDO("E:Tipo de Bultos[[1?]] de los Items estan repetidos"),
	ITEMS_TOTAL_ITEMS_DIFIERE_ENCABEZADO("E:El Total de Items del Encabezado no coincide con el Total de Items declarados"),
	ITEMS_PESO_TOTAL_DIFIERE_ENCABEZADO("E:El Total de Peso declarado no coincide con la suma de los pesos de los items del documento"),
	ITEMS_CANTIDAD_TOTAL_DIFIERE_ENCABEZADO("E:El Total de Bultos declarado no coincide con la suma de las cantidades de los items del documento"),
	CARGOS_TARIFA_MAYOR_ZERO("E:Cargo[[1?]] la tarifa del cargo debe ser mayor que cero"),
	CARGOS_SIN_TIPO_CARGO("E:Cargo[[1?]] Debe indicar el atributo [tipo-cargo]"),
	CARGOS_SIN_VALOR_MONTO("E:Cargo[[1?]], se debe indicar el Valor del Monto en el cargo"),
	CARGOS_SIN_TIPO_MONEDA("E:Cargo[[1?]], se debe indicar la Moneda en el cargo"),
	CARGOS_FLET_SIN_MONEDA("E:En Cargos para tipo de cargo FLET, la moneda del cargo debe tener un valor"),
	CARGOS_FLET_SIN_MONTO("E:En Cargos para tipo de cargo FLET, el monto del cargo debe tener un valor"),
	CARGOS_SIN_DESC("E:Cargo[[1?]], se debe indicar la descripción del cargo"),
	CARGOS_SIN_MONTO("E:Cargo[[1?]], E:En Cargos, el monto del cargo debe ser un valor numérico mayor que cero"),
	TRANSBORDOS_SIN_CODIGO("E:Transbordo[[1?]] Debe indicar el atributo [cod-lugar]"),
	TRANSBORDOS_NO_COINCIDE_DESC("E:Transbordo[[1?]], La descripcion de la Locacion[[1?]] no coincide con la descripción en los sistemas"),
	TRANSBORDOS_COD_LOC_NO_EXISTE("E:Transbordo[[1?]], el Código de la Locacion[[2?]] no se encuentra registrada en los sistemas'"),
	TRANSBORDOS_FECARRIBO_NULA("E:Transbordo[[1?]], debe consignar la Fecha de Arribo del Transbordo"),
	TRANSBORDOS_SIN_DESC("E:Transbordo[[1?]], debe consignar la Descripción del Lugar en el Transbordo"),
	VISTOSBUENOS_NO_VALIDO_TIPO("E:En Vistos Buenos, el tipo de Visto Bueno [[1?]] no corresponde"),
	CONS_NO_VALIDO_SRCEI("E:Para Consignatario,[1?]"),

	GENERAL(""),FECHAS(""),CARGOS(""),ITEMS(""),OBSERVACIONES(""),PARTICIPACIONES(""),REFERENCIAS(""),VISTOS_BUENOS(""), EMISOR(""), RUT(""), LOCACIONES(""), TRANSBORDOS("");
	
	private String texto;
	
	private TipoValidacion(String texto) {
		this.texto = texto;
	}

	public String getTexto() {
		return texto;
	}
 
	
	
	
}
