package cl.gob.sna.gtime.vo;

public enum TipoPersistencia {
	DOCDOCUMENTOBASE,
	DOCIMAGEN,
	DOCESTADOS,
	DOCTRANITEMTRANSPORTE,
	DOCTRANCARGO,
	DOCTRANVISTOSBUENOS,
	DOCTRANGCTRANSBORDOS,
	DOCTRANGUIACOURIER,
	DOCUMENTOTRANSPORTE,
	DOCTRANDOCTRANSPORTE,
	DOCLOCACIONDOCUMENTO,
	DOCRELACIONDOCUMENTO,
	DOCOBSERVACION,
	DOCFECHADOCUMENTO,
	DOCPARTICIPACION,
	DOCNOTIFICACIONBATCH,
	DOCTRANITEMPRODUCTO,
	DOCPROPAGACIONESTADOBATCH,

}
